"""Static seed data for the `components_catalog` and `examples` collections.

Authoring decisions:
- 9 components, one per supported part. The agent reads pin lists and props
  schemas to know what is wireable.
- 30 example projects covering blink, button, traffic light, servo,
  potentiometer, LCD, buzzer, 7-segment, and a few combination toys. Each has
  bilingual intent text and tags so the vector search demo plays well across
  English and Spanish prompts. We keep `cpp_hint` short - the agent uses the
  hint as inspiration and regenerates the full sketch via Blockly.
"""

from typing import Any

COMPONENTS_CATALOG: list[dict[str, Any]] = [
    {
        "type": "uno",
        "label": "Arduino UNO",
        "always_present": True,
        "pins": [f"D{i}" for i in range(2, 14)]
        + ["A0", "A1", "A2", "A3", "A4", "A5", "5V", "3V3", "GND"],
        "default_props": {},
    },
    {
        "type": "led",
        "label": "LED",
        "pins": ["anode", "cathode"],
        "props_schema": {"color": ["red", "green", "blue", "yellow"]},
        "default_props": {"color": "red"},
        "auto_companions": ["resistor"],
        "wiring_hint": "anode goes through a 220 ohm resistor to a digital pin; cathode to GND.",
    },
    {
        "type": "resistor",
        "label": "Resistor",
        "pins": ["a", "b"],
        "props_schema": {"value": ["220", "330", "1k", "10k"]},
        "default_props": {"value": "220"},
    },
    {
        "type": "pushbutton",
        "label": "Pushbutton",
        "pins": ["1a", "1b", "2a", "2b"],
        "props_schema": {"color": ["red", "green", "blue", "yellow", "black"]},
        "default_props": {"color": "blue"},
        "wiring_hint": "use INPUT_PULLUP and read LOW when pressed.",
    },
    {
        "type": "buzzer",
        "label": "Passive buzzer",
        "pins": ["1", "2"],
        "default_props": {},
        "wiring_hint": "drive with tone() on a digital pin; other leg to GND.",
    },
    {
        "type": "servo",
        "label": "Servo SG90",
        "pins": ["PWM", "VCC", "GND"],
        "default_props": {"angle": 0},
        "wiring_hint": "PWM on any digital pin; VCC to 5V, GND to GND.",
    },
    {
        "type": "potentiometer",
        "label": "Potentiometer",
        "pins": ["GND", "SIG", "VCC"],
        "default_props": {"value": 0},
        "wiring_hint": "SIG to an analog pin (default A0).",
    },
    {
        "type": "lcd1602",
        "label": "LCD 16x2 (I2C)",
        "pins": ["GND", "VCC", "SDA", "SCL"],
        "default_props": {},
        "wiring_hint": "SDA -> A4, SCL -> A5 on Arduino UNO.",
    },
    {
        "type": "seg7",
        "label": "7-segment display",
        "pins": ["A", "B", "C", "D", "E", "F", "G", "DP", "COM"],
        "default_props": {"color": "red"},
    },
]


EXAMPLES_SEED: list[dict[str, Any]] = [
    {
        "id": "ex-001",
        "title": "Blink the on-board LED",
        "intent_en": "blink the LED on pin 13 once per second",
        "tags": ["led", "blink", "timing", "starter"],
        "difficulty": 1,
        "cpp_hint": "digitalWrite + delay(500) loop",
    },
    {
        "id": "ex-002",
        "title": "Two LEDs alternating",
        "intent_en": "alternate two LEDs so one is on while the other is off",
        "tags": ["led", "blink", "alternate"],
        "difficulty": 1,
        "cpp_hint": "toggle pins 12 and 13 each 500 ms",
    },
    {
        "id": "ex-003",
        "title": "Traffic light",
        "intent_en": "three LEDs sequencing red, yellow, green like a traffic light",
        "tags": ["led", "traffic", "sequence"],
        "difficulty": 2,
        "cpp_hint": "pinMode 11, 12, 13 OUTPUT; cycle red 3s, yellow 1s, green 3s",
    },
    {
        "id": "ex-004",
        "title": "Button-controlled LED",
        "intent_en": "an LED that turns on while a button is pressed",
        "tags": ["led", "button", "input"],
        "difficulty": 1,
        "cpp_hint": "digitalRead(2) with INPUT_PULLUP and digitalWrite(13, !state)",
    },
    {
        "id": "ex-005",
        "title": "Button toggles LED on and off",
        "intent_en": "press the button once to turn the LED on, press again to turn it off",
        "tags": ["led", "button", "toggle", "state"],
        "difficulty": 2,
        "cpp_hint": "edge detection on pin 2; toggle a bool",
    },
    {
        "id": "ex-006",
        "title": "Fading LED (PWM)",
        "intent_en": "smoothly fade an LED in and out using PWM",
        "tags": ["led", "pwm", "fade", "analog"],
        "difficulty": 2,
        "cpp_hint": "analogWrite on pin 9 ramping 0..255..0",
    },
    {
        "id": "ex-007",
        "title": "Potentiometer dims an LED",
        "intent_en": "read a potentiometer and use it to set LED brightness",
        "tags": ["led", "potentiometer", "pwm", "analog"],
        "difficulty": 2,
        "cpp_hint": "analogRead(A0) / 4 -> analogWrite(9)",
    },
    {
        "id": "ex-008",
        "title": "Buzzer plays a tone",
        "intent_en": "play a single tone on a buzzer when the sketch starts",
        "tags": ["buzzer", "sound", "tone"],
        "difficulty": 1,
        "cpp_hint": "tone(8, 440, 500) in setup",
    },
    {
        "id": "ex-009",
        "title": "Happy Birthday melody",
        "intent_en": "play the Happy Birthday melody on a buzzer",
        "tags": ["buzzer", "sound", "melody", "music"],
        "difficulty": 3,
        "cpp_hint": "array of frequencies and durations; loop tone+delay",
    },
    {
        "id": "ex-010",
        "title": "Servo sweep 0 to 180",
        "intent_en": "make a servo sweep from 0 to 180 degrees back and forth",
        "tags": ["servo", "motor", "sweep"],
        "difficulty": 2,
        "cpp_hint": "Servo library, ramp angle 0..180..0",
    },
    {
        "id": "ex-011",
        "title": "Potentiometer controls a servo",
        "intent_en": "use a potentiometer to control the angle of a servo motor",
        "tags": ["servo", "potentiometer", "analog", "motor"],
        "difficulty": 2,
        "cpp_hint": "map(analogRead(A0), 0, 1023, 0, 180) -> servo.write",
    },
    {
        "id": "ex-012",
        "title": "Doorbell",
        "intent_en": "press a button to play a doorbell sound on the buzzer",
        "tags": ["buzzer", "button", "sound", "doorbell"],
        "difficulty": 2,
        "cpp_hint": "on press, tone(8, 880, 200) then tone(8, 660, 200)",
    },
    {
        "id": "ex-013",
        "title": "Hello world on LCD",
        "intent_en": "show 'Hello world' on a 16x2 I2C LCD display",
        "tags": ["lcd", "display", "hello"],
        "difficulty": 2,
        "cpp_hint": "LiquidCrystal_I2C; setCursor(0,0); print",
    },
    {
        "id": "ex-014",
        "title": "Show potentiometer value on LCD",
        "intent_en": "read a potentiometer and display its value on a 16x2 LCD",
        "tags": ["lcd", "potentiometer", "analog", "display"],
        "difficulty": 3,
        "cpp_hint": "analogRead(A0); lcd.print(value)",
    },
    {
        "id": "ex-015",
        "title": "7-segment counts 0 to 9",
        "intent_en": "count from 0 to 9 on a single 7-segment display once per second",
        "tags": ["7segment", "display", "counter", "timing"],
        "difficulty": 2,
        "cpp_hint": "segment pattern table; advance each loop",
    },
    {
        "id": "ex-016",
        "title": "7-segment counts button presses",
        "intent_en": "count how many times a button is pressed and show the digit on a 7-segment",
        "tags": ["7segment", "button", "counter", "display"],
        "difficulty": 3,
        "cpp_hint": "edge detect on pin 2; counter % 10 -> 7-segment",
    },
    {
        "id": "ex-017",
        "title": "Reaction time game",
        "intent_en": "wait a random delay then turn on an LED; measure how fast a button is pressed in response",
        "tags": ["led", "button", "game", "timing", "millis"],
        "difficulty": 3,
        "cpp_hint": "random(2000,5000) delay; millis() before and after",
    },
    {
        "id": "ex-018",
        "title": "Christmas lights",
        "intent_en": "alternate three colored LEDs in a holiday-light sequence",
        "tags": ["led", "sequence", "holiday"],
        "difficulty": 1,
        "cpp_hint": "rotating shift through 3 LEDs",
    },
    {
        "id": "ex-019",
        "title": "SOS Morse with LED",
        "intent_en": "blink an LED in Morse code spelling SOS",
        "tags": ["led", "morse", "blink"],
        "difficulty": 2,
        "cpp_hint": "short-short-short / long-long-long / short-short-short",
    },
    {
        "id": "ex-020",
        "title": "Knight Rider scanner",
        "intent_en": "scan a row of LEDs left and right like the Knight Rider car",
        "tags": ["led", "sequence", "scan"],
        "difficulty": 2,
        "cpp_hint": "index 0..N-1 then back",
    },
    {
        "id": "ex-021",
        "title": "Heartbeat LED",
        "intent_en": "make an LED pulse like a heartbeat using PWM",
        "tags": ["led", "pwm", "fade", "heartbeat"],
        "difficulty": 2,
        "cpp_hint": "two quick pulses then a pause",
    },
    {
        "id": "ex-022",
        "title": "Police lights",
        "intent_en": "alternate red and blue LEDs quickly like emergency vehicle lights",
        "tags": ["led", "alternate", "emergency"],
        "difficulty": 1,
        "cpp_hint": "fast toggle of red/blue pins",
    },
    {
        "id": "ex-023",
        "title": "Theremin-style buzzer",
        "intent_en": "use a potentiometer to change the pitch played on a buzzer in real time",
        "tags": ["buzzer", "potentiometer", "music", "analog"],
        "difficulty": 2,
        "cpp_hint": "map(analogRead, 0, 1023, 220, 880) -> tone()",
    },
    {
        "id": "ex-024",
        "title": "Dimmer with potentiometer",
        "intent_en": "read a potentiometer and use its value to dim a single LED",
        "tags": ["led", "potentiometer", "pwm", "dimmer"],
        "difficulty": 2,
        "cpp_hint": "analogRead(A0) / 4 -> analogWrite(9)",
    },
    {
        "id": "ex-025",
        "title": "Three-button mini piano",
        "intent_en": "three buttons that each play a different note on a buzzer",
        "tags": ["buzzer", "button", "music", "piano"],
        "difficulty": 3,
        "cpp_hint": "tone() with different frequencies per pin",
    },
    {
        "id": "ex-026",
        "title": "Servo door lock",
        "intent_en": "press a button to toggle a servo between locked and unlocked positions",
        "tags": ["servo", "button", "lock", "toggle"],
        "difficulty": 2,
        "cpp_hint": "on press, switch between servo.write(0) and servo.write(90)",
    },
    {
        "id": "ex-027",
        "title": "Random number on 7-segment",
        "intent_en": "show a random digit 0-9 on a 7-segment when a button is pressed",
        "tags": ["7segment", "button", "random", "game"],
        "difficulty": 2,
        "cpp_hint": "random(0, 10) on press -> segment pattern",
    },
    {
        "id": "ex-028",
        "title": "Binary counter on LEDs",
        "intent_en": "count up in binary using three LEDs, advancing once per second",
        "tags": ["led", "binary", "counter", "timing"],
        "difficulty": 3,
        "cpp_hint": "for i in 0..7, set each LED to bit of i",
    },
    {
        "id": "ex-029",
        "title": "Fake thermometer on LCD",
        "intent_en": "use a potentiometer as a fake temperature sensor and display the value on the LCD",
        "tags": ["lcd", "potentiometer", "display", "sensor"],
        "difficulty": 3,
        "cpp_hint": "map(analogRead(A0), 0, 1023, 15, 35) -> lcd.print",
    },
    {
        "id": "ex-030",
        "title": "Greeting card",
        "intent_en": "press a button to play a melody and blink a colored LED in time",
        "tags": ["buzzer", "led", "button", "music", "card"],
        "difficulty": 3,
        "cpp_hint": "on press, tone() and digitalWrite(led, HIGH) on each note",
    },
]
